{{- define "env" -}}
- name: DJANGO_DATABASE_NAME
  valueFrom:
    configMapKeyRef:
      name: database-config
      key: name
- name: DJANGO_DATABASE_HOST
  valueFrom:
    configMapKeyRef:
      name: database-config
      key: host
- name: DJANGO_DATABASE_PORT
  valueFrom:
    configMapKeyRef:
      name: database-config
      key: port
- name: DJANGO_DATABASE_USER
  valueFrom:
    secretKeyRef:
      name: database-credentials
      key: user
- name: DJANGO_DATABASE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: database-credentials
      key: password
- name: DJANGO_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: secret_key
- name: DJANGO_GITLAB_TOKEN
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: gitlab_token
- name: DJANGO_SOCIAL_AUTH_GITLAB_KEY
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: social_auth_gitlab_key
- name: DJANGO_SOCIAL_AUTH_GITLAB_SECRET
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: social_auth_gitlab_secret
- name: DJANGO_ENV
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: env
- name: DJANGO_GITLAB_CHECK_WEBHOOKS
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: gitlab_check_webhooks
- name: DOMAIN_NAME
  valueFrom:
    configMapKeyRef:
      name: global-config
      key: domain
- name: DJANGO_EMAIL_HOST
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: email.host
- name: DJANGO_EMAIL_PORT
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: email.port
- name: DJANGO_DEFAULT_FROM_EMAIL
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: email.from_email
- name: DJANGO_EMAIL_HOST_USER
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: email.user
- name: DJANGO_EMAIL_HOST_PASSWORD
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: email.password
- name: DJANGO_SLACK_TOKEN
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: slack.token
#- name: DJANGO_SENTRY_DSN
#  valueFrom:
#    secretKeyRef:
#      name: backend-secrets
#      key: sentry.dsn
- name: DJANGO_FLUENTD_LOGGER_HOST
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: logging.fluentd_host
{{- end -}}
