[tool.poetry]
name = "team-projector"
version = "0.1.0"
description = ""
authors = ["junte"]

[tool.poetry.dependencies]
python = "^3.6"
python-gitlab = "*"
python-dateutil = "*"
python-decouple = "*"
Django = "2.*"
djangorestframework = "*"
django-cors-headers = "*"
django-split-settings = "*"
django-extensions = "*"
django-filter = "*"
django-model-utils = "*"
django-health-check = "*"
django-activity-stream = "*"
psycopg2-binary = "*"
jnt-django-bitfield = "*"
jnt-django-admin-tools = "*"
social-auth-app-django = "*"
social-auth-core = "*"
celery = "*"
flower = "*"
redis = "*"
xlsxwriter = "*"
graphene-django = "*"
slackclient = "*"
uwsgi = "*"
uwsgitop = "*"
tqdm = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
pytest-django = "*"
pytest-xdist = "*"
factory-boy = "*"
flake8 = "*"
flake8-django = "*"
flake8-pytest-style = "*"
flake8-pytest = "*"
mypy = "*"
httpretty = "*"
wemake-python-styleguide = "*"
polint = "*"
dennis = "*"
safety = "*"
xenon = "*"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
