[tool.poetry]
name = "team-projector"
version = "0.1.0"
description = ""
authors = ["junte"]

[tool.poetry.dependencies]
python = "^3.6"
"psycopg2-binary" = "*"
Django = "*"
uWSGI = "*"
djangorestframework = "*"
drf-yasg = "*"
django-cors-headers = "*"
django-split-settings = "*"
django-model-utils = "*"
python-gitlab = "*"
celery = "4.1.*"
flower = "*"
redis = "*"
xlsxwriter = "*"
python-dateutil = "*"
django-admin-autocomplete-filter = "*"
django-extensions = "*"
factory-boy = "*"
django-filter = "*"
social-auth-core = "*"
social-auth-app-django = "*"
python-decouple = "*"
django-health-check = "*"
tornado = "5.*"
jnt-django-bitfield = "*"
jnt-django-admin-tools = "*"

[tool.poetry.dev-dependencies]
flake8 = "*"
ipython = "*"
mypy = "*"
xenon = "0.5.4"
pytest = "*"
pytest-cov = "*"
pytest-django = "*"
pytest-xdist = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
