[tool.poetry]
name = "team-projector"
version = "0.1.0"
description = ""
authors = ["junte"]

[tool.poetry.dependencies]
python = "^3.6"
"psycopg2-binary" = "*"
Django = "*"
uWSGI = "*"
djangorestframework = "*"
drf-yasg = "*"
django-cors-headers = "*"
django-split-settings = "*"
django-model-utils = "*"
python-gitlab = "*"
celery = "4.1.*"
flower = "*"
redis = "*"
xlsxwriter = "*"
python-dateutil = "*"
django-admin-autocomplete-filter = "*"
django-extensions = "*"
factory-boy = "*"
django-filter = "*"
social-auth-core = "*"
social-auth-app-django = "*"
python-decouple = "*"
django-health-check = "*"
tornado = "5.*"
django-bitfield = {git = "https://github.com/Junte/django-bitfield.git", tag="v1.9.5"}
django-admin-tools = {git = "https://github.com/Junte/django-admin-tools.git"}
"flake8" = "*"

[tool.poetry.dev-dependencies]
"flake8" = "*"
pytest-django = "*"
ipython = "*"
mypy = "*"
xenon = "0.5.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
