# Generated by Django 3.1.2 on 2020-10-20 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='HT__TITLE', max_length=255, unique=True, verbose_name='VN__TITLE')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='HT__TITLE', max_length=255, unique=True, verbose_name='VN__TITLE')),
            ],
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='HT__TITLE', max_length=255, unique=True, verbose_name='VN__TITLE')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('description', models.CharField(help_text='HT__DESCRIPTION', max_length=255, unique=True, verbose_name='VN__DESCRIPTION')),
                ('skill', models.ForeignKey(help_text='HT__SKILL', on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='skills.skill', verbose_name='VN__SKILL')),
            ],
            options={
                'unique_together': {('skill',)},
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='group',
            field=models.ForeignKey(help_text='HT__GROUP', on_delete=django.db.models.deletion.CASCADE, to='skills.skillgroup', verbose_name='VN__GROUP'),
        ),
        migrations.CreateModel(
            name='PositionSkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(help_text='HT__POSITION', on_delete=django.db.models.deletion.CASCADE, to='skills.position', verbose_name='VN__POSITION')),
                ('skill_level', models.ForeignKey(help_text='HT__SKILL_LEVEL', on_delete=django.db.models.deletion.CASCADE, to='skills.skilllevel', verbose_name='VN__SKILL_LEVEL')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_date', models.DateTimeField()),
                ('confirmed_by', models.ForeignKey(help_text='HT__USER', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='VN__USER')),
                ('skill_level', models.ForeignKey(help_text='HT__SKILL_LEVEL', on_delete=django.db.models.deletion.CASCADE, to='skills.skilllevel', verbose_name='VN__SKILL_LEVEL')),
                ('user', models.ForeignKey(help_text='HT__USER', on_delete=django.db.models.deletion.CASCADE, related_name='skill_levels', to=settings.AUTH_USER_MODEL, verbose_name='VN__USER')),
            ],
            options={
                'unique_together': {('user', 'confirmed_by', 'skill_level')},
            },
        ),
    ]
