# Generated by Django 3.1.2 on 2020-10-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllevel',
            name='description',
            field=models.TextField(help_text='HT__DESCRIPTION', verbose_name='VN__DESCRIPTION'),
        ),
    ]
