# Generated by Django 3.1.2 on 2020-10-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20201020_1311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skilllevel',
            unique_together={('skill', 'level')},
        ),
    ]
