# Generated by Django 3.1.2 on 2020-10-20 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0003_auto_20201020_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskilllevel',
            name='confirmed_by',
            field=models.ForeignKey(help_text='HT__CONFIRMED_BY', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='VN__CONFIRMED_BY'),
        ),
        migrations.AddConstraint(
            model_name='userskilllevel',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('confirmed_by')), name='user_can_not_be_confirmer'),
        ),
    ]
