# Generated by Django 3.1.2 on 2020-11-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_auto_20201020_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'VN__POSITION', 'verbose_name_plural': 'VN__POSITIONS'},
        ),
        migrations.AlterModelOptions(
            name='positionskilllevel',
            options={'verbose_name': 'VN__POSITION_SKILL_LEVEL', 'verbose_name_plural': 'VN__POSITION_SKILL_LEVELS'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'VN__SKILL', 'verbose_name_plural': 'VN__SKILLS'},
        ),
        migrations.AlterModelOptions(
            name='skillgroup',
            options={'verbose_name': 'VN__SKILL_GROUP', 'verbose_name_plural': 'VN__SKILL_GROUPS'},
        ),
        migrations.AlterModelOptions(
            name='skilllevel',
            options={'verbose_name': 'VN__SKILL_LEVEL', 'verbose_name_plural': 'VN__SKILL_LEVELS'},
        ),
        migrations.AlterModelOptions(
            name='userskilllevel',
            options={'verbose_name': 'VN__USER_SKILL_LEVEL', 'verbose_name_plural': 'VN__USER_SKILL_LEVELS'},
        ),
    ]
