pytest_plugins = (
    "tests.fixtures.gql",
    "tests.fixtures.gql_mock",
    "tests.fixtures.settings",
    "tests.fixtures.gitlab",
    "tests.fixtures.users",
    "tests.fixtures.requests",
    "tests.fixtures.admin",
    "tests.fixtures.team",
    "tests.fixtures.team_makers",
    "tests.fixtures.project",
    "tests.fixtures.project_makers",
    "tests.fixtures.group",
    "tests.fixtures.group_makers",
    "tests.fixtures.assets",
    "tests.fixtures.http",
    "tests.fixtures.slack",
)
