apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: worker
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "300Mi"
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          command: ["celery"]
          args: ["-A", "server.celery_app", "worker", "--concurrency", "2"]
          env:
          {{- include "env" . | nindent 12 }}
