# -*- coding: utf-8 -*-

# Generated by Django 2.1.5 on 2019-02-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_auto_20190202_1614"),
    ]

    operations = [
        migrations.AddField(
            model_name="timespend",
            name="date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="timespend",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
