# Generated by Django 2.1.7 on 2019-03-14 14:59

import apps.core.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0008_auto_20190313_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sum', apps.core.models.fields.MoneyField(decimal_places=2, help_text='HT__SUM', max_digits=14, verbose_name='VN__SUM')),
            ],
            options={
                'verbose_name': 'VN__PAYROLL',
                'verbose_name_plural': 'VN__PAYROLL',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_from', models.DateField(blank=True, help_text='HT__PERIOD_FROM', null=True, verbose_name='VN__PERIOD_FROM')),
                ('period_to', models.DateField(blank=True, help_text='HT__PERIOD_TO', null=True, verbose_name='VN__PERIOD_TO')),
                ('charged_time', models.IntegerField(help_text='HT__CHARGED_TIME', verbose_name='VN__CHARGED_TIME')),
                ('taxes', apps.core.models.fields.MoneyField(decimal_places=2, help_text='HT__TAXES', max_digits=14, verbose_name='VN__TAXES')),
                ('bonus', apps.core.models.fields.MoneyField(decimal_places=2, help_text='HT__BONUS', max_digits=14, verbose_name='VN__BONUS')),
                ('sum', apps.core.models.fields.MoneyField(decimal_places=2, help_text='HT__SUM', max_digits=14, verbose_name='VN__SUM')),
                ('total', apps.core.models.fields.MoneyField(decimal_places=2, help_text='HT__TOTAL', max_digits=14, verbose_name='VN__TOTAL')),
                ('payed', models.BooleanField(default=False, help_text='HT__PAYED', verbose_name='VN__PAYED')),
                ('created_by', models.ForeignKey(help_text='HT__CREATED_BY', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='VN__CREATED_BY')),
                ('user', models.ForeignKey(help_text='HT__USER', on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL, verbose_name='VN__USER')),
            ],
            options={
                'verbose_name': 'VN__SALARY',
                'verbose_name_plural': 'VN__SALARIES',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='spenttime',
            name='user',
            field=models.ForeignKey(help_text='HT__USER', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='VN__USER'),
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('payroll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payroll.Payroll')),
                ('description', models.TextField(help_text='HT__DESCRIPTION', verbose_name='VN__DESCRIPTION')),
            ],
            options={
                'verbose_name': 'VN__BONUS',
                'verbose_name_plural': 'VN__BONUS',
                'ordering': ('-created_at',),
            },
            bases=('payroll.payroll',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payroll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payroll.Payroll')),
            ],
            options={
                'verbose_name': 'VN__PAYMENT',
                'verbose_name_plural': 'VN__PAYMENT',
                'ordering': ('-created_at',),
            },
            bases=('payroll.payroll',),
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('payroll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payroll.Payroll')),
                ('description', models.TextField(help_text='HT__DESCRIPTION', verbose_name='VN__DESCRIPTION')),
            ],
            options={
                'verbose_name': 'VN__PENALTY',
                'verbose_name_plural': 'VN__PENALTY',
                'ordering': ('-created_at',),
            },
            bases=('payroll.payroll',),
        ),
        migrations.AddField(
            model_name='payroll',
            name='created_by',
            field=models.ForeignKey(help_text='HT__CREATED_BY', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='VN__CREATED_BY'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary',
            field=models.ForeignKey(blank=True, help_text='HT__SALARY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payroll.Salary', verbose_name='VN__SALARY'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='user',
            field=models.ForeignKey(help_text='HT__USER', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='VN__USER'),
        ),
    ]
