# -*- coding: utf-8 -*-

# Generated by Django 2.1.7 on 2019-03-14 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0010_auto_20190314_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='spenttime',
        ),
    ]
