# Generated by Django 3.0.2 on 2020-02-19 18:28

import apps.core.models.fields.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_auto_20191129_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spenttime',
            old_name='rate',
            new_name='hour_rate',
        ),
        migrations.AddField(
            model_name='spenttime',
            name='tax_rate',
            field=models.FloatField(help_text='HT__TAX_RATE', null=True, verbose_name='VN__TAX_RATE'),
        ),
        migrations.AddField(
            model_name='spenttime',
            name='tax_sum',
            field=apps.core.models.fields.money.MoneyField(decimal_places=2, default=0, help_text='HT__TAX_SUM', max_digits=14, verbose_name='VN__TAX_SUM'),
        ),
    ]
