# Generated by Django 3.0.2 on 2020-02-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_auto_20200219_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbreak',
            name='paid',
            field=models.BooleanField(default=False, help_text='HT__PAID', verbose_name='VN__PAID'),
        ),
    ]
