# Generated by Django 3.0.2 on 2020-02-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200219_2128'),
        ('payroll', '0024_workbreak_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='hour_rate',
            field=models.FloatField(default=0, help_text='HT__HOUR_RATE', verbose_name='VN__HOUR_RATE'),
        ),
        migrations.AddField(
            model_name='salary',
            name='position',
            field=models.ForeignKey(blank=True, help_text='HT__POSITION', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Position', verbose_name='VN__POSITION'),
        ),
        migrations.AddField(
            model_name='salary',
            name='tax_rate',
            field=models.FloatField(help_text='HT__TAX_RATE', null=True, verbose_name='VN__TAX_RATE'),
        ),
    ]
