# Generated by Django 3.0.2 on 2020-02-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_auto_20200220_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='tax_rate',
            field=models.FloatField(default=0, help_text='HT__TAX_RATE', verbose_name='VN__TAX_RATE'),
        ),
        migrations.AlterField(
            model_name='spenttime',
            name='tax_rate',
            field=models.FloatField(default=0, help_text='HT__TAX_RATE', verbose_name='VN__TAX_RATE'),
        ),
    ]
