# Generated by Django 3.0.2 on 2020-02-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_auto_20200220_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name="bonus",
            old_name="description",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="penalty",
            old_name="description",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="salary",
            old_name="comments",
            new_name="comment",
        ),
        migrations.AlterField(
            model_name='bonus',
            name='comment',
            field=models.TextField(help_text='HT__COMMENT', verbose_name='VN__COMMENT'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='comment',
            field=models.TextField(help_text='HT__COMMENT', verbose_name='VN__COMMENT'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='comment',
            field=models.TextField(blank=True, help_text='HT__COMMENT', verbose_name='VN__COMMENT'),
        ),
    ]
