# Generated by Django 3.0.3 on 2020-03-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_auto_20200221_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbreak',
            name='approve_state',
            field=models.CharField(choices=[('CREATED', 'CH__CREATED'), ('APPROVED', 'CH__APPROVED'), ('DECLINED', 'CH__DECLINED')], default='CREATED', help_text='HT__APPROVE_STATE', max_length=15, verbose_name='VN__APPROVE_STATE'),
        ),
        migrations.AlterField(
            model_name='workbreak',
            name='reason',
            field=models.CharField(choices=[('DAYOFF', 'CH__DAYOFF'), ('VACATION', 'CH__VACATION'), ('DISEASE', 'CH__DISEASE')], help_text='HT__REASON', max_length=15, verbose_name='VN__REASON'),
        ),
    ]
