# Generated by Django 3.0.2 on 2020-03-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_auto_20200305_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spenttime',
            name='tax_sum',
        ),
    ]
