# Generated by Django 3.0.8 on 2020-08-03 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0030_auto_20200325_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbreak',
            name='user',
            field=models.ForeignKey(help_text='HT__USER', on_delete=django.db.models.deletion.CASCADE, related_name='work_breaks', to=settings.AUTH_USER_MODEL, verbose_name='VN__USER'),
        ),
    ]
