# Generated by Django 3.1.2 on 2020-10-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_auto_20201020_1347'),
        ('payroll', '0031_auto_20200803_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='position',
            field=models.ForeignKey(blank=True, help_text='HT__POSITION', null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.position', verbose_name='VN__POSITION'),
        ),
    ]
