# Generated by Django 3.1.2 on 2020-10-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0033_auto_20201028_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbreak',
            name='paid_days',
            field=models.PositiveIntegerField(default=0, help_text='HT__PAID_DAYS', verbose_name='VN__PAID_DAYS'),
        ),
        migrations.AlterField(
            model_name='workbreak',
            name='from_date',
            field=models.DateField(help_text='HT__DATE_FROM', verbose_name='VN__DATE_FROM'),
        ),
        migrations.AlterField(
            model_name='workbreak',
            name='to_date',
            field=models.DateField(help_text='HT__DATE_TO', verbose_name='VN__DATE_TO'),
        ),
    ]
