version: '2.4'

services:
  postgres:
    image: registry.esanum.de:5000/postgres:12.1
    shm_size: '1gb'
    env_file:
    - postgres.conf
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
      target: test
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - .:/app/

volumes:
  pg_data:
