apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: beat
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "200Mi"
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          command: ["celery"]
          args: ["-A", "server.celery_app", "beat",  "-s", "/var/run/celerybeat-schedule"]
          env:
          {{- include "env" . | nindent 12 }}
          volumeMounts:
            - name: celery-beat-data
              mountPath: /var/run
      volumes:
        - name: celery-beat-data
          persistentVolumeClaim:
            claimName: celery-beat-data-pvc
