apiVersion: v1
kind: PersistentVolume
metadata:
  name: celery-beat-data-local
spec:
  storageClassName: local
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/data/celery/beat
    type: DirectoryOrCreate
