# -*- coding: utf-8 -*-

# Generated by Django 2.1.4 on 2018-12-09 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20181209_1947"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gl_username",
        ),
    ]
