# -*- coding: utf-8 -*-

# Generated by Django 2.1.4 on 2018-12-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_gl_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hour_rate",
            field=models.PositiveIntegerField(default=0, help_text="HT__HOUR_RATE", verbose_name="VN__HOUR_RATE"),
        ),
    ]
