# -*- coding: utf-8 -*-

# Generated by Django 2.1.4 on 2018-12-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_hour_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="hour_rate",
            field=models.DecimalField(decimal_places=2, default=0, help_text="HT__HOUR_RATE", max_digits=10, verbose_name="VN__HOUR_RATE"),
        ),
    ]
