# -*- coding: utf-8 -*-

# Generated by Django 2.1.7 on 2019-03-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='HT__EMAIL', max_length=150, null=True, unique=True, verbose_name='VN__EMAIL'),
        ),
    ]
