# -*- coding: utf-8 -*-

# Generated by Django 2.2.1 on 2019-06-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_customer_hour_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gl_token',
            field=models.CharField(blank=True, help_text='HT__PERSONAL_GITLAB_TOKEN', max_length=128, null=True, verbose_name='VN__PERSONAL_GITLAB_TOKEN'),
        ),
    ]
