# Generated by Django 2.2.5 on 2019-11-07 09:45

from django.db import migrations, models

import apps.users.models.validators.user


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_auto_20191029_1948"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, help_text="HT__EMAIL", max_length=150, validators=[apps.users.models.validators.user.validate_email], verbose_name="VN__EMAIL"),
        ),
    ]
