# Generated by Django 2.2.6 on 2019-11-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_auto_20191107_1245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, help_text="HT__EMAIL", max_length=150, verbose_name="VN__EMAIL"),
        ),
    ]
