# Generated by Django 2.2.7 on 2019-11-29 09:55

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_auto_20191114_1037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=bitfield.models.BitField((("DEVELOPER", "CH_DEVELOPER"), ("TEAM_LEADER", "CH_TEAM_LEADER"), ("MANAGER", "CH_MANAGER"), ("CUSTOMER", "CH_CUSTOMER"), ("SHAREHOLDER", "CH_SHAREHOLDER")), default=0),
        ),
    ]
