# Generated by Django 3.0.2 on 2020-02-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200214_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='HT__TITLE', max_length=255, unique=True, verbose_name='VN__TITLE')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='taxes',
            new_name='tax_rate',
        ),
        migrations.AddField(
            model_name='user',
            name='annual_paid_work_breaks_days',
            field=models.IntegerField(default=0, help_text='HT__ANNUAL_PAID_WORK_BREAKS_DAYS', verbose_name='VN__ANNUAL_PAID_WORK_BREAKS_DAYS'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tax_rate',
            field=models.FloatField(default=0, help_text='HT__TAX_RATE', verbose_name='VN__TAX_RATE'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, help_text='HT__POSITION', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Position', verbose_name='VN__POSITION'),
        ),
    ]
