# Generated by Django 3.0.3 on 2020-03-05 13:18

import jnt_django_toolbox.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200219_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=jnt_django_toolbox.models.fields.BitField([('DEVELOPER', 'CH__DEVELOPER'), ('TEAM_LEADER', 'CH__TEAM_LEADER'), ('MANAGER', 'CH__MANAGER'), ('CUSTOMER', 'CH__CUSTOMER'), ('SHAREHOLDER', 'CH__SHAREHOLDER')], default=0),
        ),
    ]
