# Generated by Django 3.0.4 on 2020-03-25 09:55

from django.db import migrations, models

import apps.core.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_notify_pipeline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tax_rate',
            field=models.FloatField(default=0, help_text='HT__TAX_RATE', validators=[apps.core.models.validators.tax_rate_validator], verbose_name='VN__TAX_RATE'),
        ),
    ]
