# Generated by Django 3.1.1 on 2020-09-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200325_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='HT__IS_STAFF', verbose_name='VN__IS_STAFF'),
        ),
    ]
