# Generated by Django 3.1.2 on 2020-10-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200924_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gl_id',
            field=models.PositiveIntegerField(blank=True, help_text='HT__GITLAB_ID', null=True, unique=True, verbose_name='VN__GITLAB_ID'),
        ),
    ]
