# Generated by Django 3.1.2 on 2020-10-20 11:10

from django.db import migrations


def forwards_func(apps, schema_editor):
    Position = apps.get_model("skills", "Position")
    UserPosition = apps.get_model("users", "Position")

    for position in UserPosition.objects.all():
        Position.objects.update_or_create(
            id=position.pk,
            defaults={"title": position.title},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_auto_20201012_1224"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
