# Generated by Django 3.1.2 on 2020-10-20 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_auto_20201020_1347'),
        ('users', '0028_auto_20201020_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, help_text='HT__POSITION', null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.position', verbose_name='VN__POSITION'),
        ),
    ]
