from .all_work_breaks import AllWorkBreaksConnectionField
from .all_bonuses import AllBonusesConnectionField
from .all_penalties import AllPenaltiesConnectionField
from .all_salaries import AllSalariesConnectionField
