# -*- coding: utf-8 -*-

# Generated by Django 2.1.4 on 2018-12-08 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_id', models.PositiveIntegerField(help_text='HT__GITLAB_ID', verbose_name='VN__GITLAB_ID')),
                ('gitlab_url', models.URLField(help_text='HT__GITLAB_URL', verbose_name='VN__GITLAB_URL')),
                ('title', models.CharField(help_text='HT__TITLE', max_length=255, verbose_name='VN__TITLE')),
                ('time_estimate', models.PositiveIntegerField(help_text='HT__TIME_ESTIMATE', null=True, verbose_name='VN__TIME_ESTIMATE')),
                ('time_spend', models.PositiveIntegerField(help_text='HT__TIME_SPEND', null=True, verbose_name='VN__TIME_SPEND')),
                ('employee', models.ForeignKey(blank=True, help_text='HT__EMPLOYEE', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='VN__EMPLOYEE')),
            ],
            options={
                'verbose_name': 'VN__ISSUE',
                'verbose_name_plural': 'VN__ISSUES',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_id', models.PositiveIntegerField(help_text='HT__GITLAB_ID', verbose_name='VN__GITLAB_ID')),
                ('gitlab_url', models.URLField(help_text='HT__GITLAB_URL', verbose_name='VN__GITLAB_URL')),
                ('title', models.CharField(help_text='HT__TITLE', max_length=255, verbose_name='VN__TITLE')),
            ],
            options={
                'verbose_name': 'VN__PROJECT',
                'verbose_name_plural': 'VN__PROJECTS',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_id', models.PositiveIntegerField(help_text='HT__GITLAB_ID', verbose_name='VN__GITLAB_ID')),
                ('gitlab_url', models.URLField(help_text='HT__GITLAB_URL', verbose_name='VN__GITLAB_URL')),
                ('title', models.CharField(help_text='HT__TITLE', max_length=255, verbose_name='VN__TITLE')),
            ],
            options={
                'verbose_name': 'VN__PROJECT_GROUP',
                'verbose_name_plural': 'VN__PROJECT_GROUPS',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, help_text='HT__GROUP', null=True, on_delete=django.db.models.deletion.SET_NULL, to='development.ProjectGroup', verbose_name='VN__GROUP'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(blank=True, help_text='HT__PROJECT', null=True, on_delete=django.db.models.deletion.SET_NULL, to='development.Project', verbose_name='VN__PROJECT'),
        ),
    ]
