# Generated by Django 2.1.4 on 2018-12-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_auto_20181208_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='HT__PARENT', null=True, on_delete=django.db.models.deletion.CASCADE, to='development.ProjectGroup', verbose_name='VN__PARENT'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='gitlab_last_sync',
            field=models.DateTimeField(blank=True, help_text='HT__GITLAB_LAST_SYNC', null=True, verbose_name='VN__GITLAB_LAST_SYNC'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gitlab_last_sync',
            field=models.DateTimeField(blank=True, help_text='HT__GITLAB_LAST_SYNC', null=True, verbose_name='VN__GITLAB_LAST_SYNC'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='gitlab_last_sync',
            field=models.DateTimeField(blank=True, help_text='HT__GITLAB_LAST_SYNC', null=True, verbose_name='VN__GITLAB_LAST_SYNC'),
        ),
    ]
