# Generated by Django 2.1.4 on 2019-01-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0009_projectgroup_full_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='HT__TITLE', max_length=255, verbose_name='VN__TITLE')),
                ('color', models.CharField(help_text='HT__COLOR', max_length=10, verbose_name='VN__COLOR')),
            ],
        ),
    ]
