# Generated by Django 2.1.4 on 2019-01-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0010_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='labels',
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='issues', to='development.Label'),
        ),
    ]
