# -*- coding: utf-8 -*-

# Generated by Django 2.1.5 on 2019-01-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0013_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='total_time_spent',
        ),
        migrations.AddField(
            model_name='issue',
            name='total_spent',
            field=models.PositiveIntegerField(help_text='HT__TOTAL_SPENT', null=True, verbose_name='VN__TOTAL_SPENT'),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('time_spend', 'Time spend'), ('reset_spend', 'Reset spend')], help_text='HT__TYPE', max_length=20, verbose_name='VN__TYPE'),
        ),
    ]
