# Generated by Django 2.1.5 on 2019-01-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0014_auto_20190128_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('-created_at',), 'verbose_name': 'VN__ISSUE', 'verbose_name_plural': 'VN__ISSUES'},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='total_spent',
        ),
        migrations.AddField(
            model_name='issue',
            name='total_time_spent',
            field=models.PositiveIntegerField(help_text='HT__TOTAL_TIME_SPENT', null=True, verbose_name='VN__TOTAL_TIME_SPENT'),
        ),
    ]
