# -*- coding: utf-8 -*-

# Generated by Django 2.1.5 on 2019-02-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development", "0016_auto_20190202_1614"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
