# -*- coding: utf-8 -*-

# Generated by Django 2.1.5 on 2019-02-04 12:57

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("development", "0017_note_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
