# Generated by Django 2.1.7 on 2019-03-11 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('development', '0021_auto_20190311_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(help_text='HT__TITLE', max_length=255, unique=True, verbose_name='VN__TITLE'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'user')},
        ),
    ]
