# Generated by Django 2.1.7 on 2019-03-13 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('development', '0022_auto_20190311_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='employee',
            new_name='user',
        )
    ]
