# -*- coding: utf-8 -*-

# Generated by Django 2.1.7 on 2019-04-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0026_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(help_text='HT__DESCRIPTION', verbose_name='VN__DESCRIPTION'),
        ),
    ]
