# -*- coding: utf-8 -*-

# Generated by Django 2.1.7 on 2019-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0028_auto_20190404_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(blank=True, help_text='HT__DUE_DATE', null=True, verbose_name='VN__DUE_DATE'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='start_date',
            field=models.DateField(blank=True, help_text='HT__START_DATE', null=True, verbose_name='VN__START_DATE'),
        ),
    ]
