# -*- coding: utf-8 -*-

# Generated by Django 2.2 on 2019-04-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0034_auto_20190416_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='members',
            field=models.ManyToManyField(to='development.ProjectMember'),
        ),
    ]
