# -*- coding: utf-8 -*-

# Generated by Django 2.2 on 2019-04-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("development", "0040_auto_20190418_1147"),
        ("development", "0040_auto_20190417_1150"),
    ]

    operations = [
    ]
