# Generated by Django 2.2 on 2019-04-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0043_issue_participants'),
        ('development', '0043_issue_epic'),
    ]

    operations = [
    ]
