# Generated by Django 2.2 on 2019-05-14 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0044_merge_20190429_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Issue',
            name='epic',
            field=models.IntegerField(),
        ),
        migrations.RenameModel('Epic', 'Feature'),
        migrations.AlterField(
            model_name='Issue',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='development.Feature'),
        ),
        migrations.RenameField('Issue', 'epic', 'feature'),
        migrations.AlterField(
            model_name='feature',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature',
                                    to='development.Milestone'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='development.Milestone'),
        ),
    ]
