# Generated by Django 2.2 on 2019-05-14 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('development', '0044_merge_20190429_1121'),
    ]

    operations = [
        migrations.RenameModel('Epic', 'Feature'),
        migrations.RenameField('Issue', 'epic', 'feature'),
    ]
