# -*- coding: utf-8 -*-

# Generated by Django 2.2 on 2019-05-17 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0045_auto_20190514_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_merged',
            field=models.BooleanField(default=False),
        ),
    ]
