# Generated by Django 2.2 on 2019-05-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0046_auto_20190515_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='feature',
        ),
    ]
