# Generated by Django 2.2.1 on 2019-05-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0047_auto_20190522_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='state',
            field=models.CharField(blank=True, help_text='HT__STATE', max_length=255, null=True, verbose_name='VN__STATE'),
        ),
    ]
