# Generated by Django 2.2 on 2019-05-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0048_mergerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gl_last_merge_requests_sync',
            field=models.DateTimeField(blank=True, help_text='HT__MERGE_REQUESTS_SYNC', null=True, verbose_name='VN__GITLAB_MERGE_REQUESTS_SYNC'),
        ),
    ]
