# -*- coding: utf-8 -*-

# Generated by Django 2.2.1 on 2019-05-30 14:52

import bitfield.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('development', '0049_auto_20190527_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gl_last_merge_requests_sync',
            field=models.DateTimeField(blank=True, help_text='HT__MERGE_REQUESTS_SYNC', null=True, verbose_name='VN__GITLAB_MERGE_REQUESTS_SYNC'),
        ),
        migrations.CreateModel(
            name='MergeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_id', models.PositiveIntegerField(help_text='HT__GITLAB_ID', unique=True, verbose_name='VN__GITLAB_ID')),
                ('gl_url', models.URLField(help_text='HT__GITLAB_URL', unique=True, verbose_name='VN__GITLAB_URL')),
                ('gl_last_sync', models.DateTimeField(blank=True, help_text='HT__GITLAB_LAST_SYNC', null=True, verbose_name='VN__GITLAB_LAST_SYNC')),
                ('gl_iid', models.PositiveIntegerField(help_text='HT__GITLAB_INTERNAL_ID', null=True, verbose_name='VN__GITLAB_INTERNAL_ID')),
                ('title', models.CharField(help_text='HT__TITLE', max_length=255, verbose_name='VN__TITLE')),
                ('time_estimate', models.PositiveIntegerField(help_text='HT__TIME_ESTIMATE', null=True, verbose_name='VN__TIME_ESTIMATE')),
                ('total_time_spent', models.PositiveIntegerField(help_text='HT__TOTAL_TIME_SPENT', null=True, verbose_name='VN__TOTAL_TIME_SPENT')),
                ('state', models.CharField(blank=True, choices=[('closed', 'closed'), ('merged', 'merged'), ('opened', 'opened')], help_text='HT__STATE', max_length=255, null=True, verbose_name='VN__STATE')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='HT__USER', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee_merge_requests', to=settings.AUTH_USER_MODEL, verbose_name='VN__USER')),
                ('author', models.ForeignKey(blank=True, help_text='HT__USER', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_merge_requests', to=settings.AUTH_USER_MODEL, verbose_name='VN__USER')),
                ('labels', models.ManyToManyField(blank=True, related_name='merge_requests', to='development.Label')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='development.Milestone')),
                ('project', models.ForeignKey(blank=True, help_text='HT__PROJECT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests', to='development.Project', verbose_name='VN__PROJECT')),
            ],
            options={
                'verbose_name': 'VN__MERGE_REQUEST',
                'verbose_name_plural': 'VN__MERGE_REQUESTS',
                'ordering': ('-created_at',),
            },
        ),
    ]
