# Generated by Django 2.2.2 on 2019-06-11 10:21

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0051_auto_20190607_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='roles',
            field=bitfield.models.BitField((('leader', 'CH_LEADER'), ('developer', 'CH_DEVELOPER'), ('watcher', 'CH_WATCHER')), default=0),
        ),
    ]
