# -*- coding: utf-8 -*-

# Generated by Django 2.2.2 on 2019-06-27 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("development", "0053_auto_20190627_1855"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together={("team", "user")},
        ),
    ]
