# -*- coding: utf-8 -*-

# Generated by Django 2.2.2 on 2019-08-06 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0056_auto_20190801_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gl_avatar',
            field=models.URLField(blank=True, help_text='HT__GITLAB_AVATAR', null=True, verbose_name='VN__GITLAB_AVATAR'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='gl_avatar',
            field=models.URLField(blank=True, help_text='HT__GITLAB_AVATAR', null=True, verbose_name='VN__GITLAB_AVATAR'),
        ),
    ]
