# -*- coding: utf-8 -*-

# Generated by Django 2.2.5 on 2019-09-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0058_auto_20190906_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='merge_requests',
            field=models.ManyToManyField(blank=True, related_name='issues', to='development.MergeRequest'),
        ),
    ]
