# Generated by Django 2.2.5 on 2019-09-09 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0058_auto_20190906_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergerequest',
            name='issues',
            field=models.ManyToManyField(blank=True, related_name='issue_merge_requests', to='development.Issue'),
        ),
    ]
