# Generated by Django 2.2.5 on 2019-10-04 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("development", "0059_issue_merge_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mergerequest",
            name="state",
            field=models.CharField(blank=True, choices=[("opened", "opened"), ("merged", "merged"), ("closed", "closed")], help_text="HT__STATE", max_length=255, null=True, verbose_name="VN__STATE"),
        ),
        migrations.AlterField(
            model_name="mergerequest",
            name="user",
            field=models.ForeignKey(blank=True, help_text="HT__USER", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="merge_requests", to=settings.AUTH_USER_MODEL, verbose_name="VN__USER"),
        ),
        migrations.AlterField(
            model_name="note",
            name="type",
            field=models.CharField(choices=[("time_spend", "Time spend"), ("reset_spend", "Reset spend"), ("moved_from", "Moved from")], help_text="HT__TYPE", max_length=20, verbose_name="VN__TYPE"),
        ),
    ]
