# Generated by Django 3.0.2 on 2020-02-13 15:08

from django.db import migrations

from apps.development.models.ticket import TicketState


def set_ticket_default_state(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Ticket = apps.get_model('development', 'Ticket')
    Ticket.objects.filter(state='').update(state=TicketState.CREATED)

class Migration(migrations.Migration):

    dependencies = [
        ('development', '0070_auto_20200213_1807'),
    ]

    operations = [
        migrations.RunPython(set_ticket_default_state),
    ]
