# Generated by Django 3.0.3 on 2020-02-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0072_auto_20200214_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('FEATURE', 'CH_FEATURE'), ('IMPROVEMENT', 'CH_IMPROVEMENT'), ('BUG_FIXING', 'CH_BUG_FIXING')], default='FEATURE', help_text='HT__TYPE', max_length=50, verbose_name='VN__TYPE'),
        ),
    ]
