# Generated by Django 3.0.3 on 2020-02-14 17:24

import jnt_django_toolbox.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0073_auto_20200214_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='roles',
            field=jnt_django_toolbox.models.fields.BitField([('LEADER', 'CH_LEADER'), ('DEVELOPER', 'CH_DEVELOPER'), ('WATCHER', 'CH_WATCHER')], default=0),
        ),
    ]
