# Generated by Django 3.0.3 on 2020-02-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0074_auto_20200214_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('TIME_SPEND', 'CH_TIME_SPEND'), ('RESET_SPEND', 'CH_RESET_SPEND'), ('MOVED_FROM', 'CH_MOVED_FROM')], help_text='HT__TYPE', max_length=20, verbose_name='VN__TYPE'),
        ),
    ]
