# Generated by Django 3.0.3 on 2020-02-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0075_auto_20200214_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('DEVELOPER', 'CH_DEVELOPER'), ('PROJECT_MANAGER', 'CH_PROJECT_MANAGER'), ('CUSTOMER', 'CH_CUSTOMER')], help_text='HT__ROLE', max_length=20, verbose_name='VN__ROLE'),
        ),
    ]
