# Generated by Django 3.0.3 on 2020-02-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0076_auto_20200214_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='state',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'CH_ACTIVE'), ('CLOSED', 'CH_CLOSED')], help_text='HT__STATE', max_length=20, verbose_name='VN__STATE'),
        ),
    ]
