# Generated by Django 3.0.3 on 2020-03-05 13:18

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0077_auto_20200214_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.CharField(blank=True, choices=[('OPENED', 'CH__OPENED'), ('CLOSED', 'CH__CLOSED')], help_text='HT__STATE', max_length=255, verbose_name='VN__STATE'),
        ),
        migrations.AlterField(
            model_name='mergerequest',
            name='state',
            field=models.CharField(blank=True, choices=[('OPENED', 'CH__OPENED'), ('MERGED', 'CH__MERGED'), ('CLOSED', 'CH__CLOSED')], help_text='HT__STATE', max_length=255, verbose_name='VN__STATE'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='state',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'CH__ACTIVE'), ('CLOSED', 'CH__CLOSED')], help_text='HT__STATE', max_length=20, verbose_name='VN__STATE'),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('TIME_SPEND', 'CH__TIME_SPEND'), ('RESET_SPEND', 'CH__RESET_SPEND'), ('MOVED_FROM', 'CH__MOVED_FROM')], help_text='HT__TYPE', max_length=20, verbose_name='VN__TYPE'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('DEVELOPER', 'CH__DEVELOPER'), ('MANAGER', 'CH__MANAGER'), ('CUSTOMER', 'CH__CUSTOMER')], help_text='HT__ROLE', max_length=20, verbose_name='VN__ROLE'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='roles',
            field=bitfield.models.BitField([('LEADER', 'CH__LEADER'), ('DEVELOPER', 'CH__DEVELOPER'), ('WATCHER', 'CH__WATCHER')], default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(blank=True, choices=[('CREATED', 'CH__CREATED'), ('PLANNING', 'CH__PLANNING'), ('DOING', 'CH__DOING'), ('TESTING', 'CH__TESTING'), ('ACCEPTING', 'CH__ACCEPTING'), ('DONE', 'CH__DONE')], default='CREATED', help_text='HT__STATE', max_length=50, verbose_name='VN__STATE'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('FEATURE', 'CH__FEATURE'), ('IMPROVEMENT', 'CH__IMPROVEMENT'), ('BUG_FIXING', 'CH__BUG_FIXING')], default='FEATURE', help_text='HT__TYPE', max_length=50, verbose_name='VN__TYPE'),
        ),
    ]
