# Generated by Django 3.0.4 on 2020-03-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0078_auto_20200305_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, default=""),
        ),
    ]
