# Generated by Django 3.0.4 on 2020-03-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0079_issue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('TIME_SPEND', 'CH__TIME_SPEND'), ('RESET_SPEND', 'CH__RESET_SPEND'), ('MOVED_FROM', 'CH__MOVED_FROM'), ('COMMENT', 'CH__COMMENT')], help_text='HT__TYPE', max_length=20, verbose_name='VN__TYPE'),
        ),
    ]
