# Generated by Django 3.1.2 on 2020-10-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0082_auto_20200914_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='gl_id',
            field=models.PositiveIntegerField(help_text='HT__GITLAB_ID', unique=True, verbose_name='VN__GITLAB_ID'),
        ),
    ]
