# Generated by Django 3.1.2 on 2020-10-16 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('development', '0083_auto_20201007_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(blank=True, help_text='HT__AUTHOR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_issues', to=settings.AUTH_USER_MODEL, verbose_name='VN__AUTHOR'),
        ),
    ]
