# Generated by Django 3.1.2 on 2020-10-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0084_issue_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='state',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'CH__STATE_ACTIVE'), ('CLOSED', 'CH__STATE_CLOSED')], help_text='HT__STATE', max_length=20, verbose_name='VN__STATE'),
        ),
    ]
