# Generated by Django 3.1.2 on 2020-10-21 08:28

from django.db import migrations

from apps.development.models.project import ProjectState


def update_project_states(apps, schema_editor):
    Project = apps.get_model("development", "Project")
    Project.objects.filter(is_active=False).update(state=ProjectState.ARCHIVED)


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0086_project_state'),
    ]

    operations = [
        migrations.RunPython(update_project_states),
    ]
