# Generated by Django 3.1.2 on 2020-10-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0086_auto_20201021_1006'),
        ('development', '0088_remove_project_is_archived'),
    ]

    operations = [
    ]
