# Generated by Django 3.1.2 on 2020-11-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0094_auto_20201123_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='role',
        ),
    ]
