# Generated by Django 3.1.4 on 2020-12-03 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0096_auto_20201123_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inherited', models.BooleanField(default=False)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.project')),
            ],
            options={
                'unique_together': {('milestone', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ProjectGroupMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inherited', models.BooleanField(default=False)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.milestone')),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.projectgroup')),
            ],
            options={
                'unique_together': {('milestone', 'project_group')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='milestones',
            field=models.ManyToManyField(related_query_name='project', through='development.ProjectMilestone', to='development.Milestone'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='milestones',
            field=models.ManyToManyField(related_query_name='project_group', through='development.ProjectGroupMilestone', to='development.Milestone'),
        ),
    ]
