# Generated by Django 3.1.3 on 2020-12-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0097_auto_20201203_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estimate',
            field=models.PositiveIntegerField(default=0, help_text='HT__ESTIMATE', verbose_name='VN__ESTIMATE'),
        ),
    ]
