# Generated by Django 3.1.3 on 2020-12-16 09:09

import apps.development.models.issue
import apps.development.models.note
import apps.development.models.ticket
from django.db import migrations
import jnt_django_toolbox.models.fields.enum


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0098_ticket_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=jnt_django_toolbox.models.fields.enum.EnumField(blank=True, choices=[('OPENED', 'CH__OPENED'), ('CLOSED', 'CH__CLOSED')], enum=apps.development.models.issue.IssueState, help_text='HT__STATE', verbose_name='VN__STATE'),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=jnt_django_toolbox.models.fields.enum.EnumField(choices=[('TIME_SPEND', 'CH__TIME_SPEND'), ('RESET_SPEND', 'CH__RESET_SPEND'), ('MOVED_FROM', 'CH__MOVED_FROM'), ('COMMENT', 'CH__COMMENT')], enum=apps.development.models.note.NoteType, help_text='HT__TYPE', verbose_name='VN__TYPE'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=jnt_django_toolbox.models.fields.enum.EnumField(blank=True, choices=[('CREATED', 'CH__CREATED'), ('PLANNING', 'CH__PLANNING'), ('DOING', 'CH__DOING'), ('TESTING', 'CH__TESTING'), ('ACCEPTING', 'CH__ACCEPTING'), ('DONE', 'CH__DONE')], default='CREATED', enum=apps.development.models.ticket.TicketState, help_text='HT__STATE', verbose_name='VN__STATE'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=jnt_django_toolbox.models.fields.enum.EnumField(blank=True, choices=[('FEATURE', 'CH__FEATURE'), ('IMPROVEMENT', 'CH__IMPROVEMENT'), ('BUG_FIXING', 'CH__BUG_FIXING')], default='FEATURE', enum=apps.development.models.ticket.TicketType, help_text='HT__TYPE', verbose_name='VN__TYPE'),
        ),
    ]
