# Generated by Django 3.1.4 on 2020-12-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0099_auto_20201216_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ('title',), 'verbose_name': 'VN__LABEL', 'verbose_name_plural': 'VN__LABELS'},
        ),
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ('user__login',), 'verbose_name': 'VN__PROJECT_MEMBER', 'verbose_name_plural': 'VN__PROJECT_MEMBERS'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('user__login',), 'verbose_name': 'VN__TEAM_MEMBER', 'verbose_name_plural': 'VN__TEAM_MEMBERS'},
        ),
    ]
