# Generated by Django 3.1.12 on 2021-06-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0100_auto_20201224_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgroupmilestone',
            options={'verbose_name': 'VN__PROJECT_GROUP_MILESTONE', 'verbose_name_plural': 'VN__PROJECT_GROUP_MILESTONES'},
        ),
        migrations.AlterModelOptions(
            name='projectmilestone',
            options={'verbose_name': 'VN__PROJECT_MILESTONE', 'verbose_name_plural': 'VN__PROJECT_MILESTONES'},
        ),
    ]
